apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubevirt.io/v1","kind":"VirtualMachine","metadata":{"annotations":{},"name":"wh-labocp-004.wh2.lab.jpmchase.net","namespace":"wvmtesting"},"spec":{"dataVolumeTemplates":[{"apiVersion":"cdi.kubevirt.io/v1beta1","kind":"DataVolume","metadata":{"name":"root-vol107"},"spec":{"source":{"http":{"url":"http://10.14.222.30:8080/rhel-8.10-x86_64-kvm.qcow2"}},"storage":{"resources":{"requests":{"storage":"30Gi"}}}}}],"running":true,"template":{"spec":{"architecture":"amd64","domain":{"devices":{"disks":[{"disk":{"bus":"virtio"},"name":"rootdisk"},{"disk":{"bus":"virtio"},"name":"cloudinitdisk"}],"interfaces":[{"bridge":{},"model":"virtio","name":"default"}]},"machine":{"type":"pc-q35-rhel9.4.0"},"memory":{"guest":"4Gi"},"resources":{}},"networks":[{"name":"default","pod":{}}],"volumes":[{"dataVolume":{"name":"root-vol107"},"name":"rootdisk"},{"cloudInitNoCloud":{"userData":"#cloud-config\nuser: cloud-user\npassword: a23456\nchpasswd: { expire: False }\nhostname: wwh-labocp-004.wh2.lab.jpmchase.net\nmanage_etc_hosts: true\nnetwork:\n  version: 2\n  ethernets:\n    eth0:\n      dhcp6: false\n      dhcp4: false\n      accept-ra: false\n      addresses:\n        - 10.14.221.134/26\n      gateway4: 10.240.46.129\n      nameservers:\n        addresses:\n          - 10.240.47.3\n          - 10.240.46.3\n      ipv6-privacy: false\n      ipv6-address-generation: eui64                      "},"name":"cloudinitdisk"}]}}}}
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
  resourceVersion: '170139759'
  name: wh-labocp-004.wh2.lab.jpmchase.net
  uid: a734ce91-2987-4ba0-9731-e5662021dfc6
  creationTimestamp: '2025-07-20T03:18:52Z'
  generation: 1
  managedFields:
    - apiVersion: kubevirt.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
        'f:spec':
          .: {}
          'f:dataVolumeTemplates': {}
          'f:running': {}
          'f:template':
            .: {}
            'f:spec':
              .: {}
              'f:architecture': {}
              'f:domain':
                .: {}
                'f:devices':
                  .: {}
                  'f:disks': {}
                  'f:interfaces': {}
                'f:machine':
                  .: {}
                  'f:type': {}
                'f:memory':
                  .: {}
                  'f:guest': {}
                'f:resources': {}
              'f:networks': {}
              'f:volumes': {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2025-07-20T03:18:52Z'
    - apiVersion: kubevirt.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:kubevirt.io/latest-observed-api-version': {}
            'f:kubevirt.io/storage-observed-api-version': {}
          'f:finalizers':
            .: {}
            'v:"kubevirt.io/virtualMachineControllerFinalize"': {}
      manager: virt-controller
      operation: Update
      time: '2025-07-20T03:18:52Z'
    - apiVersion: kubevirt.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:printableStatus': {}
          'f:runStrategy': {}
          'f:conditions': {}
          .: {}
          'f:ready': {}
          'f:volumeSnapshotStatuses': {}
          'f:observedGeneration': {}
          'f:created': {}
          'f:desiredGeneration': {}
      manager: virt-controller
      operation: Update
      subresource: status
      time: '2025-07-20T03:19:59Z'
  namespace: wvmtesting
  finalizers:
    - kubevirt.io/virtualMachineControllerFinalize
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: root-vol107
      spec:
        source:
          http:
            url: 'http://10.14.222.30:8080/rhel-8.10-x86_64-kvm.qcow2'
        storage:
          resources:
            requests:
              storage: 30Gi
  running: true
  template:
    metadata:
      creationTimestamp: null
    spec:
      architecture: amd64
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - bridge: {}
              model: virtio
              name: default
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 4Gi
        resources: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - dataVolume:
            name: root-vol107
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: a23456
              chpasswd: { expire: False }
              hostname: wwh-labocp-004.wh2.lab.jpmchase.net
              manage_etc_hosts: true
              network:
                version: 2
                ethernets:
                  eth0:
                    dhcp6: false
                    dhcp4: false
                    accept-ra: false
                    addresses:
                      - 10.14.221.134/26
                    gateway4: 10.240.46.129
                    nameservers:
                      addresses:
                        - 10.240.47.3
                        - 10.240.46.3
                    ipv6-privacy: false
                    ipv6-address-generation: eui64                      
          name: cloudinitdisk
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: '2025-07-20T03:19:49Z'
      status: 'True'
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: null
      message: All of the VMI's DVs are bound and not running
      reason: AllDVsReady
      status: 'True'
      type: DataVolumesReady
    - lastProbeTime: null
      lastTransitionTime: null
      message: 'cannot migrate VMI which does not use masquerade, bridge with kubevirt.io/allow-pod-bridge-network-live-migration VM annotation or a migratable plugin to connect to the pod network'
      reason: InterfaceNotLiveMigratable
      status: 'False'
      type: LiveMigratable
    - lastProbeTime: '2025-07-20T03:19:58Z'
      lastTransitionTime: null
      status: 'True'
      type: AgentConnected
  created: true
  desiredGeneration: 1
  observedGeneration: 1
  printableStatus: Running
  ready: true
  runStrategy: Always
  volumeSnapshotStatuses:
    - enabled: true
      name: rootdisk
    - enabled: false
      name: cloudinitdisk
      reason: 'Snapshot is not supported for this volumeSource type [cloudinitdisk]'

------------------------------------------------------------------------------


apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: wh-labocp-004.wh2.lab.jpmchase.net
  namespace: wvmtesting
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: root-vol107
      spec:
        source:
          http:
            url: 'http://10.14.222.30:8080/rhel-8.10-x86_64-kvm.qcow2'
        storage:
          resources:
            requests:
              storage: 30Gi
  running: true
  template:
    spec:
      architecture: amd64
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - bridge: {}
              model: virtio
              name: default
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 4Gi
        resources: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - dataVolume:
            name: root-vol107
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: a23456
              chpasswd: { expire: False }
              hostname: wwh-labocp-004.wh2.lab.jpmchase.net
              manage_etc_hosts: true
              network:
                version: 2
                ethernets:
                  eth0:
                    dhcp6: false
                    dhcp4: false
                    accept-ra: false
                    addresses:
                      - 10.14.221.134/26
                    gateway4: 10.240.46.129
                    nameservers:
                      addresses:
                        - 10.240.47.3
                        - 10.240.46.3
          name: cloudinitdisk
