apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdata
  namespace: testproject1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-storagecluster-ceph-rbd-virtualization
