apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vmautonewimage10
  namespace: testproject1
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: vol95
      spec:
        source:
          http:
            url: 'http://10.14.222.30:8080/Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2'
            #url: 'http://10.14.222.30:8080/img_ovlt_rhel_9_9.6.1_2025-07-09-100051.qcow2'
        storage:
          resources:
            requests:
              storage: 30Gi
  running: true
  template:
    spec:
      architecture: amd64
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 4Gi
        resources: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - dataVolume:
            name: vol95
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: a23456
              chpasswd: { expire: False }
          name: cloudinitdisk
